site_name: Appunti
site_author: Muhammad Athallah
site_description: >-
  Un sito web dedicato agli appunti dei corsi di italiano offerti da Universitas Indonesia.
theme:
  name: material
  language: en
  icon:
    logo: material/school
  favicon: assets/img/logo.png
  features:
    - navigation.tabs
    - navigation.indexes
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: red
      toggle:
        icon: material/weather-night
        name: Passa alla modalità oscura
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: red
      toggle:
        icon: material/weather-sunny
        name: Passa alla modalità luce

nav:
  - Homepage:
    - index.md
  - Italiano di Base A:
    - lingua-a/index.md
  - Italiano di Base B:
    - lingua-b/index.md
  - Cultura:
    - cultura/index.md
  - Storia:
    - storia/index.md
  - Miscellaneo:
    - miscellaneo/index.md
    - BBC Talk Italian: miscellaneo/bbc-talk-italian.md
    - Musica: miscellaneo/musica.md
    - FSI Courses: miscellaneo/fsi.md